server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/seed
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:1234}
cors:
  allowed:
    api: /**
    method: '*'
security:
  patterns:
    ignoring:
      GET:
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html/**
        - /api/users/nickname/duplication
        - /api/users/username/duplication
        - /health

      POST:
        - /api/users/signin
        - /api/users/signup
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
    permit-all:
      GET: [ ]
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
      OPTIONS: /**
jwt:
  issuer: sfam
  client-secret:
  accessToken:
    header: atoken
    expiry-seconds: 21600
  refreshToken:
    header: rtoken
    expiry-seconds: 28800
feign:
  client:
    config:
      default:
        loggerLevel: basic
division:
  key: ${DIVISION_KEY:CEB52025-E065-364C-9DBA-44880E3B02B8}
  domain: ${DIVISION_DOMAIN:http://localhost:8080}

kakao:
  local:
    header: KakaoAK